/**
 * Build script — the same two-artifact shape as the sibling plugin.
 *
 * 1. `lib/index.mjs` — host half: plain ESM for Node; the Cordis loader needs one
 *    entry point per profile row (this half installs nothing).
 * 2. `lib/client.js` — browser half: DSH's client module system does not consume
 *    ES modules, it evaluates one script calling
 *    `window.__ModuleLoader__.load({ id, factory })` whose factory returns an
 *    object carrying `apply` (+ `inject`). The banner/footer pair synthesises
 *    that CommonJS closure — including the `module`/`exports` shim, without which
 *    esbuild's own `module.exports = __toCommonJS(...)` is a ReferenceError.
 *
 * Verification is a real load test, not a grep: the finished bundle is evaluated
 * in a `node:vm` sandbox with a stubbed `window.__ModuleLoader__` and a working
 * `require`, and the factory's return value is asserted to carry `apply`/`inject`.
 */
import { build } from 'esbuild'
import { mkdirSync, readFileSync, rmSync, statSync } from 'node:fs'
import { builtinModules, createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { runInNewContext } from 'node:vm'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

/** The id the client module table composes on: the npm package name. */
const PLUGIN_ID = pkg.name

/** Modules the web shell shares into the frozen table (never bundled). */
const CLIENT_EXTERNALS = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  'cordis',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-locale',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-web-react',
  '@deepseek-ai/dsh-client-ui-conversation',
  '@deepseek-ai/dsh-client-modules',
  'dsh-better-sidebar',
  'dsh-better-sidebar/client',
  'dsh-better-sidebar/client/service',
]

const NODE_BUILTINS = new Set([...builtinModules, ...builtinModules.map(id => `node:${id}`)])

/** Absolute path of one artifact. */
const out = name => join(root, 'lib', name)

rmSync(join(root, 'lib'), { recursive: true, force: true })
mkdirSync(join(root, 'lib'), { recursive: true })

// ── Host half ────────────────────────────────────────────────────────────────
await build({
  absWorkingDir: root,
  entryPoints: ['src/index.ts'],
  outfile: out('index.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  sourcemap: true,
  external: [...NODE_BUILTINS, 'node:*', '@deepseek-ai/cordis', 'cordis'],
  logLevel: 'warning',
})

// ── Browser half ─────────────────────────────────────────────────────────────
await build({
  absWorkingDir: root,
  entryPoints: ['src/client/index.tsx'],
  outfile: out('client.js'),
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  sourcemap: true,
  external: CLIENT_EXTERNALS,
  loader: { '.css': 'text' },
  define: {
    'process.env.NODE_ENV': '"production"',
    'import.meta.env.MODE': '"production"',
  },
  banner: {
    js: [
      `// ${PLUGIN_ID} — browser half (client module-loader bundle).`,
      '// Generated by scripts/build.mjs from src/client/**; edit the sources, not this file.',
      'window.__ModuleLoader__.load({',
      `  id: ${JSON.stringify(PLUGIN_ID)},`,
      '  factory: (require) => {',
      '    var module = { exports: {} };',
      '    var exports = module.exports;',
    ].join('\n'),
  },
  footer: {
    js: '    return module.exports;\n  },\n});',
  },
  logLevel: 'warning',
})

// ── Build gates ──────────────────────────────────────────────────────────────
const clientPath = out('client.js')
const client = readFileSync(clientPath, 'utf8')

if (!client.includes('window.__ModuleLoader__.load({')) {
  throw new Error('client bundle is missing the __ModuleLoader__.load registration')
}
if (!client.includes('var module = { exports: {} };') || !client.includes('var exports = module.exports;')) {
  throw new Error('client bundle is missing the CommonJS module/exports shim')
}
for (const builtin of NODE_BUILTINS) {
  if (client.includes(`require("${builtin}")`)) {
    throw new Error(`client bundle requests Node builtin \`${builtin}\``)
  }
}

// The real gate: evaluate the bundle the way the browser module loader will.
const sandboxRequire = createRequire(pathToFileURL(join(root, 'package.json')).href)
let registration
const sandbox = {
  window: {
    __ModuleLoader__: {
      load(spec) {
        registration = spec
      },
    },
  },
  console,
  require: sandboxRequire,
  process: { env: { NODE_ENV: 'production' } },
}
runInNewContext(client, sandbox, { filename: 'client.js' })

if (registration === undefined) throw new Error('__ModuleLoader__.load() was never called by the client bundle')
if (registration.id !== PLUGIN_ID) {
  throw new Error(`client bundle registered id "${registration.id}", expected "${PLUGIN_ID}"`)
}
if (typeof registration.factory !== 'function') throw new Error('__ModuleLoader__.load() was given no factory')

const exportsObject = registration.factory(sandboxRequire)
if (typeof exportsObject.apply !== 'function') {
  throw new Error('factory() did not export `apply` — DSH would load the plugin and do nothing')
}
if (!Array.isArray(exportsObject.inject) || exportsObject.inject.length === 0) {
  throw new Error('factory() did not export a non-empty `inject` array')
}

const kb = path => (statSync(path).size / 1024).toFixed(1)
console.log(`[${PLUGIN_ID}] lib/index.mjs  ${kb(out('index.mjs'))} KB`)
console.log(`[${PLUGIN_ID}] lib/client.js  ${kb(clientPath)} KB  (id: ${registration.id})`)
console.log(`[${PLUGIN_ID}] build OK — load-tested: apply() + inject ${JSON.stringify(exportsObject.inject)}`)
